### ISSUE TITLE
JIRA issue workflow and backporting

### ISSUE THREAD

**Issue by HendrikThePendric** [dhis2/notes#22] opened 2019-03-05 09:45 UTC
I have some concerns about the current workflow and where back-porting fits into this.

When an issue is get the the **TESTING** status, the testers expect to be able to test on master, and all version for which a backport is required. So effectively, that means we are expected to backport the code, **before** the issue has been fully tested.

This bothers me because for the older versions (i.e. v30) we don't have any kind of staging environment. You could say that we are pushing untested code into production. I know that in practice the problem is less extreme than I phrased it just now, but in essence this is what is happening.

For issues that require back-porting, I would like to suggest the following workflow:
1. In progress
2. In review
3. **Testing (in master)**
4. **Needs update (to do the back-ports)**
5. Retesting
6. Done

What do you think?

Perhaps there are reasons why I shouldn't be worried about our current workflow. Or perhaps you have already worked out a workflow that makes even more sense... If so, please let me know :)

**Comment by ismay** [comment] 2019-03-05 10:06
I agree. It feels quite fragile. Also, not testing on master would be even better in my opinion. Creating a PR, testing from that and _then_ merging to master seems a lot more robust to me.

**Comment by varl** [comment] 2019-03-05 10:10
Pinging @Philip-Larsen-Donnelly for this.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-03-05 10:22
@HendrikThePendric The workflow you suggest _is_ (or should be) the expected current workflow!

However, the goal _is_ also to use the PRs as the staging area, and shift most of the testing there (as ismay suggests). We are working on this: new infrastructure and processes for core (to build and deploy each PR); and tools like Netlify for apps (to accomplish the same). Stay tuned over the next months as we start to get this in place. The QA team will be working with devs to make this happen in a coordinated way!

**Comment by Philip-Larsen-Donnelly** [comment] 2019-03-05 10:26
![image](https://user-images.githubusercontent.com/35666657/53798868-6879a880-3f39-11e9-9e78-7884d47d58d3.png)

**Comment by ismay** [comment] 2019-03-05 10:46
@Philip-Larsen-Donnelly The tests under "Continuous Integration", they're done whilst the PR hasn't been merged, or after? Because travis for example tests on the merge between the source branch and the upstream branch. So functionally that would be the same as testing on master after a merge, without the difficulties in having to roll back if tests fail when it's already been merged.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-03-05 10:58
@ismay  The CI is on the master. I would consider the travis example you give as part of the PR testing (more-or-less the same as rebasing the feature branch).
The CI has a slightly different focus; there may be other integration issue or different classes of tests (e.g. long running or complex non-functional testing). It also captures things that like direct commits (*gasp!*).

The above scheme is supposed to be generic to both core and apps, but of course there will be slight differences in tools and processes.

**Comment by varl** [comment] 2019-03-05 12:14
>4. Needs update (to do the back-ports)

There is a bit of JIRA ping-pong going on here if we are supposed to first fix an issue and merge it to master, then assign it to QA, then get back an OK to go ahead and backport it to other target versions, and then assign it to QA again. The context switching leads to mistakes.

This is in the happy case where it passes QA. Even more ping-pongs occur in failure situations.

We know the target versions up front, so why not just fix and merge the patch to all branches and _then_ move the issue to _Testing_ in JIRA so QA can test all of the versions in one go?

**Comment by HendrikThePendric** [comment] 2019-03-05 13:03
@Philip-Larsen-Donnelly Very happy to hear that what I propose is supposed to happen already. I will start implementing this workflow myself.

@varl I don't agree with what you say here:
> We know the target versions up front, so why not just fix and merge the patch to all branches and _then_ move the issue to _Testing_ in JIRA so QA can test all of the versions in one go?
Suppose I work on an issue that needs to be back-ported to v30, and my changes have introduced a massive 🐛 (bug), which wasn't spotted during my own tests, nor during the peer review.

The issue will now be merged into master and the backport branches, and go into the TESTING phase. Let's call this `momentA`. Suppose the issue-tester now identifies the bug, and puts my issue into NEEDS UPDATE status.

I will work on the issue again, create a PR with the fix, merge into the Master branch and all the backport branches again, and put the issue into RETESTING phase. This would be `momentB`.

So, in the time between `momentA` and `momentB`, the v30 build will have had this bug present. If we were to follow the steps I outlined, this would not have been the case. With my scenario the bug would have only been on the master branch.

And obviously, if more iterations are required, between a first attempt and a fully working resolution, the problem only gets exacerbated.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-03-05 14:40
At the testing phase, the qa team (or other tester) will test on all versions that have been implemented at that time (the dev may need to indicate this in the comment) and push back to NEEDS UPDATE if any of the target versions are not yet implemented or fail the testing. This works with both models.
Hendrik's approach is the safest, and is recommended, but it is acceptable to follow the Varl approach for low-risk changes, where it may be more convenient for the dev. When we achieve full testing at PR, the risk of _early_ backporting becomes a moot point; there is a risk of wasted effort, but the dev should be able to evaluate that and make an appropriate choice for their particular case.

**Comment by varl** [comment] 2019-03-05 16:33
`<rant>`
I do not think that it makes sense to set something to _testing_ when we _know_ that it's not complete enough for a final QA verification. That builds ping-pong into the process, forces the developer _and_ the tester to switch contexts back and forth, and introduces delays into an async process (imagine when different time zones is a factor).
`</rant>`

To clarify a bit, I don't view the _testing_ step in JIRA as the point where testing happens. I view that as the **hand-off point** between the `<dev>` team to the QA team for _verification_.

When an issue is in the _review_ state, the `<dev>` team should check that they have done everything they need to do for QA to successfully do a **verification** on the entire issue, and that means the reviewer needs to check that:

- Tests are created
- PRs are open against all target versions
- PRs pass the tests for all target versions
- Documentation update PRs are up for all target versions
- Merge all PRs to respective base branch (master, v31, v30, etc)
- Hand off issue to QA

In short my principle is:

**QA should be able to close an issue if it passes the final quality gate.** If it bounces back from _testing_, that is a failure of our development process, it should not bounce back by process design.

Thus I conclude that the JIRA steps are confusing and substitute my own definitions :clown_face::

- _In review_ === Testing (done by `<dev>` team)
- _Testing_ === Verification (done by QA)

Yes, this is a huge pain in the ass to do and adds a burden to the `<dev>` teams, though shifting that pain to the QA team is not fair either. Maybe it would even speed up implementation of automated functional tests using Cypress so we could run the test cases automatically against all target versions ... :thinking:

>When we achieve full testing at PR, the risk of early backporting becomes a moot point [...]

Yep, I think this is the correct workflow, and we as developers are capable of doing this **manually** today, as we can run the application locally connected to e.g. play.dhis2.org/dev, play.dhis2.org/2.31.1, etc. by changing a config file. Sorry for blowing the whistle on this. :wink: 

However, it _is_ exactly what a service like Netlify would automate for us, and if we think that it's a good idea, we should do it even if we cannot get it automated. 

It's not perfect, and you can go a bit further using the build system by making a proper feature build.

**Comment by HendrikThePendric** [comment] 2019-03-06 09:11
What you outline above would indeed reduce the chance of testers finding anything wrong. I think I get what you mean reg. QA doing verification, and devs doing testing. This makes sense.

However, the steps outlined above still mean that the code is merged into the v30 production build BEFORE the QA has verified the issue was fixed. This isn't right IMO, especially for bigger issues.

The solution I suggested involved some ping-pong-ing of JIRA statuses. I can see why this isn't ideal. But it does facilitate a process that makes sense to me personally: get verification that something has been solved correctly, before rolling it out to other places. The verification step is there for a reason. Even if the dev team tests more rigorously - reducing the amount of cases where the QA team will put the issue in NEEDS UPDATE status - these cases will still occur. And if so, this mean back-porting everything twice, and having a broken solution in v30 production for a while.

The above are just my opinions and personal preferences. I am happy to work in whatever way is expected. But, as it stands, I am not sure what the expectations are. Reading @Philip-Larsen-Donnelly comment makes me think that the way of working I outlined in the issue description is acceptable. But I don't think @varl agrees....

So it would be great if we could end this issue with a comment that outlines the DHIS2 consensus on what is/are the recommended way(s) of working.

**Comment by varl** [comment] 2019-03-06 12:35
### Ref. production branches

`master` and `v31` aren't production branches in the sense they were before, @Philip-Larsen-Donnelly actively tags a new production build as e.g. `2.31.1` from the `v31` branch so in those cases I don't see having a broken `master`/`v31` branch for a while as a problem.

Not sure about `v30` and `v29`, they might still be on the old release process, but they are also not built as often. Unless triggered manually, they build every night at around 02:00.

**Comment by varl** [comment] 2019-03-06 12:35
### Backporting a second/third/fourth time when a bug sneaks in

If the same bug is introduced across all branches, then it is a simple merge from a common `patch-branch` to each of the base branches. You get 4 PRs from a single branch, so I don't see that as a big problem. Annoying as Hell; yes, yes it is.

**Comment by varl** [comment] 2019-03-06 12:37
### Agree? Disagree?

I object to the principle of building in back-and-forth into a process when it is possible to define a robust, simple, process which empowers everyone to optimize their own team's workflow with as few dependencies as possible.

I think it's fair to follow both workflows, but I think neither of the workflows should _be the formal_ workflow as they are both flawed.

**The formal workflow needs to have the trait of automation.** 

Building in the ping-pong between the dev team and qa team causes hiccups in the automation.

Say that we implement fully automated functional tests for a feature which is going to get backported. We are confident it works, but we only merge it to a single branch. QA steps in and verifies that it is indeed correct. Now we go back and merge the remaining branches. Now QA steps in again and tests the remaining branches. Now we've spent man-hours (maybe even waited a day) for practically no reason.

**Comment by varl** [comment] 2019-03-06 12:46
>The verification step is there for a reason. Even if the dev team tests more rigorously and reduces the amount of cases where the QA team puts an issue in NEEDS UPDATE status - these cases will still occur. And if so, this means back-porting everything twice, and having a broken solution in v30 production for a while.

We all just want to deliver code which we know works, but I think a side effect of the ping-pong process is that the pressure to guarantee that the code works as intended gets shifted to the QA team, away from the devs that wrote it. The pressure shouldn't just be shifted from one team to another team. We should figure out a way to reduce the pressure from building up.

These are the problems I am sensing from this discussion:
 
1. Problem: _We are scared of introducing bugs when merging code_
  Solution: ???

2. Problem: _We don't know if a feature is functional or not_
  Solution : ???

3. Problem: _We have a low confidence in our code, so we want someone to verify it externally for correctness_
  Solution: ???

4. Problem: _We feel we don't have time to do the investments in test automation because there is too much pressure to deliver quantity of functionality and bug fixes_
  Solution: ???

5. Problem: _Backporting is very painful and time consuming_
  Solution: ???

**Comment by varl** [comment] 2019-03-06 12:53
> So it would be great if we could end this issue with a comment that outlines the DHIS2 consensus on what is/are the recommended way(s) of working.

@Philip-Larsen-Donnelly owns the process of the QA team, so he decides how the interface between the dev teams and the QA team has to be for the QA team to do its job efficiently.

From there each dev team has the freedom to figure out how to best satisfy the contract of that interface, so we can do our job efficiently (self organizing teams).

**Comment by Philip-Larsen-Donnelly** [comment] 2019-03-06 13:48
There are issues that will reduce the risk of early backports, and therefore avoiding the ping-pong:
1) Patch vs. Production: Indeed 2.31 and master are indeed a little safer in terms of not being considered "stable" branches. 29 and 30 are still on the old model (we are piloting the approach with 2.31 at the moment). Hopefully, later in the year we will move to patch releases for all supported versions. We are trying to encourage the community to move towards patch releases, but we cannot count on it - not yet at least.
2) App versions might not require so much back-porting if we embrace the feature toggling approach more.
3) Shifting testing into the PR, as discussed. _In this model the issue transfers from In Review to Testing within the PR, and the QA team essentially close the PR. Issues that haven't passed QA aren't merged_. 

However, like Viktor, I would like to discourage the idea that all of the testing against requirements is done by QA (and that an issue can be thrown to the QA team to see if it bounces back before committing the changes to other branches). The devs should understand the expected functionality, and should be able to test it themselves to a reasonable level of confidence before handing it on. This is true of "single Target version" issues as well as those requiring backports. The backports force it out into the open a bit more should force you to ask yourself, "what is the risk with backporting immediately?" and "how can I mitigate that without pushing to the QA team?" (I think this is what @varl is getting at, and if we don't address that then process changes such as the points above could actually encourage the _wrong_ behaviour - i.e. there is no risk to a "production" build so just push to QA). 

The QA team will continue to follow the approach I outlined, i.e. test what is ready and push back if elements are missing. But I think it is good for NEEDS UPDATE to have some sort of negative connotation; we should try to minimise NEEDS UPDATE and if it is frequent it should make us ask questions about the process.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-03-06 13:51
I want to point out that I don't see the QA team and the devs at a "them" and "us", but rather all part of the same team; with both potentially supporting each other at either side of the "hand-off".

**Comment by varl** [comment] 2019-03-06 14:17
>I want to point out that I don't see the QA team and the devs at a "them" and "us", but rather all part of the same team; with both potentially supporting each other at either side of the "hand-off".

I completely agree.

I should have worded "_dev team_" and "_qa team_" as "_agents of the dev process_" and "_agents of the qa process_" to be specific. Anyone can be an agent in either process independently of team position.

I still think that the "dev process" and the "qa process" needs an interface so each process can support the other while still being flexible in its own approach to satisfy the interface/contract. The dev process should be able to change without affecting the qa process and vice-versa.

**Comment by HendrikThePendric** [comment] 2019-03-06 14:47
Thanks for all the input @varl and @Philip-Larsen-Donnelly. My main concern was for branches like v30 which don't yet have patch releases. So I am very happy to hear that we will move to patch releases for all supported versions later this year. This is a proper solution.

In the interim, I will try to work as @varl outlined, apart from issues that I personally classify as high risk. For these I will not backport to v30 until the other branches have been found to work correctly. I will place a comment to explain about this when I move the issue to the TESTING stage.

**Closed** 2019-04-10 05:42 UTC
Labels: discussion
