### ISSUE TITLE
war and docker release schemes

### ISSUE THREAD

**Issue by Philip-Larsen-Donnelly** [dhis2/notes#48] opened 2019-05-22 08:48 UTC
We are trying to come up with a more structured and consistent nomenclature for our release artifacts.
The basic idea for war file production is something like:

---

1. *Stable releases* - available on releases.dhis2.org

- `2.32.0`
- `2.31.3`
- ...

2. *Nightly (/canary) releases* - avalable in a _slightly different_ location - for folks who want the "latest" build

- `nightly/2.32`? (`canary/2.32`?)
- `nightly/2.31`?
- ...

_The idea is to give people the option of a nightly build (cf. Chrome canary) (but not give them EVERY single build throughout the day!)_

3. *Latest build* - Available in _another_ location - just for core team/ testing

- `latest/2.32`?
- `latest/2.31`?

This is the very latest build. _Note that this might be the same core commit, with same or different app commits w.r.t the previous build._

---

Another point is that we will start to make use of Viktor's build acrobatics to keep an index of builds (without having to store previous war files indefinitely). I.e. Each build has a kind of "fingerprint" based on the core commit and the apps-bundle.json containing the app commits. The idea would be to keep an index of the builds - with this _metadata_ as well as checksums etc. - so that we have everything we need to identify and recreate a bulid (If we need to - _whether we actually need to is a bit debatable, but there are certainly use cases for debugging implementation issues, and if we keep the effort low then I think it is good practice_). *We are of course aware that the separation of apps from core probably removes the need to store the apps-bundle.json* - but it is worth thinking about the implications of this.

**_Please add your thoughts on this, taking also docker image production into account!_**

**Comment by varl** [comment] 2019-05-22 09:00
An aligned version for the Docker image tags of my last suggestion in the on-going Slack-discussion:

---

#### Release

Tag structure: `{version}(-{variant})`

- `dhis2/core:2.32.0`, `dhis2/core:latest`, `dhis2/core:2.32.0-tomcat9`, `dhis2/core:2.32.0-alpine`
- `dhis2/core:2.31.3`

#### Nightly: repo `core-nightly`

Tag structure: `{branch}-{date/timestamp}(-{variant})`

Examples:
- `dhis2/core-nightly:2.32-20190522`
- `dhis2/core-nightly:2.31-20190522`
- `dhis2/core-nightly:master-20190522`

#### Development

Tag structure: `{branch}(-{variant})`

for development we could use the branch names- `dhis2/core-dev:master`

Examples:
- `dhis2/core-dev:master`
- `dhis2/core-dev:2.32`
- `dhis2/core-dev:2.31`

For PR images we can use a short hash combined with a trimmed branch name to follow the Docker tag rules:

> A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

Tag structure: `{short hash}-{trimmed branch name}`

Examples:
- `dhis2/core-dev:a1b2c3d-my-feature-branch`
- `dhis2/core-dev:dea2345-another-feature-branch`

**Comment by varl** [comment] 2019-05-22 09:07
>_We are of course aware that the separation of apps from core probably removes the need to store the `apps-bundle.json` - but it is worth thinking about the implications of this._

Currently the JSON is created build time, but I think that it should eventually be built runtime by the backend. It can figure out what revision of an app is _installed_ instead of _bundled_. With that we could put it into the build system and create an artifact which matches the setup of an external instance for debugging/reproducing, etc.

We will still need the ability to create "Fat WARs" with all the applications necessary for an instance to be operational in e.g. field deployment scenarios where online installations of applications are impossible.

There are a few other use-cases as well, so I think that the mechanism should be improved rather than removed as we move to a full separation.

**Comment by ismay** [comment] 2019-05-22 09:29
Personally, the main thing I'd like beyond what we have currently, is docker images tagged with a commit hash. Not all of them, but just some, so that I can pin to a specific image and be sure things won't change. It's happened to me a couple of times that I have a working backend locally, and it breaks because of an update to the image.

Now of course, I could make sure to not use docker pull, but this'd make things a bit more explicit. Plus, I can be very specific when encountering an issue and point to the hash, instead of having to figure out whether I'm really running the latest image.

**Comment by varl** [comment] 2019-05-22 09:43
@ismay Generally that means you would want to use the `core-nightly` channel (has a date/timestamp) or the stable `core` channel in the scheme I outlined.

If you want the "latest and greatest" you'd run from the `core-dev` images (this is what `core` is now).

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-22 09:46
@ismay - ~For a stable image, would it be enough to use either a formal release or a "nightly"  with the timestamp scheme varl suggests above?~ varl beat me to it!

@varl - for PR images could we incorporate the PR ID? - that is what I was thinking of for the wars. Something like:
`PR/#3353` (with or without '#')

**Comment by varl** [comment] 2019-05-22 09:53
@Philip-Larsen-Donnelly yeah, that's a better idea than a short hash: `pr-{pull-id}-{trimmed branch name}`

I can update the suggestion above.

`/` and `#` will have to be dropped though from the tag.

Full tag name restrictions [quoted](https://docs.docker.com/engine/reference/commandline/tag/):

>A tag name must be valid ASCII and may contain lowercase and uppercase letters, digits, underscores, periods and dashes. A tag name may not start with a period or a dash and may contain a maximum of 128 characters.

**Comment by varl** [comment] 2019-05-22 10:09
It seemed during the discussion that `core-canary` was popular, so just mentally search and replace `core-nightly`.

Personally I think a canary release is more formal than a nightly build and that our "canary release" is actually the RC-build we cut on feature freeze and ask the DHIS2 Community to start testing.

That said, I don't mind if we want to co-opt it for nightly builds.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-22 10:18
Well, Chrome use "canary" for nightly builds (https://www.google.com/chrome/canary/) so I guess that may be familiar/acceptable to many.

The `/` in my war file schema was more like a real path:

- `https://releases.dhis2.org/2.32.0/dhis.war`
- `https://releases.dhis2.org/canary/2.32/dhis.war`
- `https://releases.dhis2.org/latest/2.32/dhis.war`
- `https://releases.dhis2.org/PR/3353/dhis.war`

i.e. instead of the current
- `https://releases.dhis2.org/2.32/dhis.war`
- `https://releases.dhis2.org/2.32/2.32.0/dhis.war`

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-22 10:19
I suppose we could also call them something other than dhis.war!? :grimacing:

**Comment by varl** [comment] 2019-05-22 12:11
If we change from `dhis.war` to something else this needs to be updated: https://docs.dhis2.org/2.32/en/implementer/html/install_server_setup.html#install_tomcat_dhis2_installation.

Consider this a todo; it is not an argument against renaming the `war`-file.

**Comment by varl** [comment] 2019-05-22 12:14
I like having the version in the name, makes it a lot easier to distinguish two downloads from each other.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-22 12:14
@varl Yes, agreed. We probably have to update that anyway - as well as communicating the release schemas to the community/implementers. The canary change alone would break most people update scripts no doubt!

**Comment by varl** [comment] 2019-05-23 13:16
It looks like https://github.com/dhis2/dhis2-core/pull/3326 is aligned with https://github.com/dhis2/notes/issues/48#issuecomment-494717208 and can be merged. Is that correct, @vilkg?

**Comment by vilkg** [comment] 2019-05-23 13:18
I think so, @varl. The only thing I see missing is nightly repo, but perhaps we could set up some automated docker workflow to push whatever is latest in dev repo every night?

**Comment by varl** [comment] 2019-05-23 13:31
Looks like `core` and `core-dev` is settled. 👍 

For canary builds, looks like @Philip-Larsen-Donnelly intends there to only be a single artifact which is replaced every night: `https://releases.dhis2.org/canary/2.32.war`.

Vs. the suggestion that it has a timestamp to be able to figure out from what day it is from: `dhis2/core-nightly:2.32-20190523`.

Would be nice to accommodate for both, e.g. `dhis2/core-nightly:2.32` would pull the latest available 2.32, e.g. be an alias for: `dhis2/core-nightly:2.32-20190523`

I think that would be nice for the `WAR`-file too: `https://releases.dhis2.org/canary/2.32.war` would be an alias to `https://releases.dhis2.org/canary/2.32-20190523.war` one day and the next canary release the next day.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-23 14:50
@varl I'm not against the timestamp version for the nightly's. (For the war, as far as I am aware S3 doesn't support alias/links so the "alias" version is simply a copy - but that's not such a big deal).

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-25 13:40
There are a few related issues, from a delivery perspective, that I would like to address here before closing this discussion completely; as I think they have a meaningful impact on how we proceed.

## Fixed releases should be identical in war and docker.
I believe that the docker pipeline builds dhis2 independently, right? This means that the stable releases are identical, but the canary (daily releases) may not be; a small time variation may pull in different apps. I think we should try to avoid this. Solutions I can think of are:
- pull the releases.dhis2.org war builds into the docker image
- build the docker image using the package parameters from the releases.dhis2.war builds

## Catalogue/Index of deterministic build (package) parameters
I think we should have a strategy for recording the extra metadata (at least the commit ids of core and apps-bundle.json) needed to re-generate the builds. This is what I mean by "package parameters" above and also means we don't have to store things indefinitely. It will also help us to define...

## Image lifecycles
I think we should agree how long we want to keep things _as a minimum_. My feelings are
- Stable releases can be kept indefinitely.
- Canary releases should be available from "the patch release before last".
- Dev releases might be useful going back 1 milestone.
- PR releases can be removed following successful merge into the main branch.

By "available" I mean that the artifact is stored and immediately available. For "older" versions I would envisage that we can pick from the "Catalogue/Index" above and generate a war/docker image on demand. 
_There is nothing wrong with keeping artifacts a bit longer - as long as there is no extra cost involved. What I am tyring to do is establish a minimum "service" that we can offer/support._

**Comment by varl** [comment] 2019-05-28 06:14
> I believe that the docker pipeline builds dhis2 independently, right? This means that the stable releases are identical, but the canary (daily releases) may not be; a small time variation may pull in different apps. I think we should try to avoid this.

I think that's correct. I wouldn't go so far to say that they are identical as even if they are built using the same _package parameters_, the build environment is different. They should be functionally equivalent, but the byte size and hash won't match from a Jenkins-built `WAR` and the `WAR` bundled in the Docker image.

**There is a bug with the Docker images however:**
The Docker build has a drawback of not having the Git repository information available so it fails to set the core commit revision:

- https://github.com/dhis2/dhis2-core/blob/0460082f65826af04d1298d97cc7bca2ef3f47af/dhis-2/pom.xml#L277-L283
- https://github.com/dhis2/dhis2-core/blob/667efb56e42659569e5904d92c492f57e6a4c7ea/dhis-2/dhis-services/dhis-service-core/src/main/java/org/hisp/dhis/system/DefaultSystemService.java#L206

This is a problem because the system info end-point in a Docker build will [not report a valid revision](https://dhis2.vardevs.se/dev/api/system/info):

```
"revision": "fatal: Not a git repository (or any of the parent directories): .git"
```

**Because of this problem, I don't think that the Docker images of dhis2 are valid replacements for the `WAR`-file produced by Jenkins.** So this becomes a question of build authority.

Currently the authoritative build creator is the Jenkins environment. That is what we use to produce the official `WAR`-files. It is the official baseline.

At the moment it makes sense to copy the _authoritative_ `WAR`-file into the Docker image, rather than copy the `WAR` file _out_ from the Docker build since the Docker environment does not have access to the Git repository.

The alternative is to switch to a model where the authoritative build creator is Docker, and Jenkins is just the executor. There are some modifications we need to do in that case:

- Docker should build dhis2 from the Git source tree so it has access to the commit history and can extract a revision.
- We need to give Jenkins access to the `WAR`-file produced inside of the Docker image, so it can continue the process of publishing `WAR`-files to S3, or move that process to the Docker build as well.

I think this makes sense to do long-term, as at that point you have your build environment reproducible between executors. The price to pay is tighter coupling to Docker.

> I think we should have a strategy for recording the extra metadata (at least the commit ids of core and apps-bundle.json) needed to re-generate the builds.

A `gzip` with the name `dhis2-core-{channel}-{version}-{commit-id}.gz` with the generated `apps-bundle.json` as contents will be roughly **1.1 KB** a pop. We could keep a few of those around without it being a storage problem even if we decide to put more metadata in there.

**Comment by varl** [comment] 2019-05-28 06:28
Would be pretty nifty to have a `Dockerfile` which you just feed a `.gz` and it breaks it down and uses the parts to recreate a core build.. 🤔

**Comment by varl** [comment] 2019-05-28 06:30
## `system/info` "not a git repository" bug

I think we can fix the bug by removing `.git` from the `.dockerignore` file here: https://github.com/dhis2/dhis2-core/blob/master/.dockerignore#L1

**Comment by amcgee** [comment] 2019-05-28 07:43
>     * https://releases.dhis2.org/2.32.0.war

Jumping in to an earlier point - I also like having the version in the WAR filename, but we should endeavor to keep the product name (`dhis(2)`) in the filename as well - when a user installs a WAR file into their Tomcat instance, it's nice to know what that WAR file is without renaming.

**Comment by amcgee** [comment] 2019-05-28 07:47
> @varl I'm not against the timestamp version for the nightly's. (For the war, as far as I am aware S3 doesn't support alias/links so the "alias" version is simply a copy - but that's not such a big deal).

I'm not sure it's as necessary to have an aliased nightly "latest" in the WAR file.  If we really wanted to do that we would just have a script update an HTML link on the `releases` page to point to the latest canary (which includes the date in the filename).

**Comment by vilkg** [comment] 2019-05-28 09:22
I was thinking this solution could be simple: 
Every night, take whatever is in core-dev, append timestamp to the tag and push to core-canary. We should be certain, that what is there during the night is the latest built image for every branch I think.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-28 09:28
> I'm not sure it's as necessary to have an aliased nightly "latest" in the WAR file. If we really wanted to do that we would just have a script update an HTML link on the `releases` page to point to the latest canary (which includes the date in the filename).

I think most sysadmins use scripts, pulling directly from S3, so a stable name makes things a lot simpler. On the one hand we do want to discourage people from taking the canaries into production, but we _don't_ want to discourage them taking into dev and testing.

**Comment by Philip-Larsen-Donnelly** [comment] 2019-05-28 09:49
> Would be pretty nifty to have a `Dockerfile` which you just feed a `.gz` and it breaks it down and uses the parts to recreate a core build..

I would like to be able to do this in both Docker and native War pipelines! 

@vilkg made the point that we are using (and planning to continue using) docker for testing, so we should only push the war to releases.dhis2.org _if_ the testing on the docker build is successful. 
1. If docker is the authoritative build creator, then this is easy.
2. Or... we could create the Jenkins build from the successful docker `.gz` params.
3. Or... there are still options where we keep Jenkins as the authoritative build creator, but there's a bit more juggling involved.

I'm a little concerned about having too tight coupling with Docker.

**Comment by varl** [comment] 2019-05-28 10:03
> I'm a little concerned about having too tight coupling with Docker.

Me too in general. The container tech shouldn't be a lock-in.

**Comment by varl** [comment] 2019-05-28 11:12
> > ```
> > * https://releases.dhis2.org/2.32.0.war
> > ```
> 
> Jumping in to an earlier point - I also like having the version in the WAR filename, but we should endeavor to keep the product name (`dhis(2)`) in the filename as well - when a user installs a WAR file into their Tomcat instance, it's nice to know what that WAR file is without renaming.

This is true for all of the WAR-files across channels. Should we prefix all of them with `dhis2`? We could include channel as well. `dhis2-{channel}-{version/branch}.war`?

**Comment by amcgee** [comment] 2019-05-28 11:59
I think that makes sense to me, it makes it very clear what WAR file you’re dealing with.

**Comment by varl** [comment] 2019-05-28 12:49
> @vilkg made the point that we are using (and planning to continue using) docker for automated testing, so we should only push the war to releases.dhis2.org _if_ the testing on the docker build is successful.

Good point, that. It goes hand-in-hand with only creating a single `WAR`-file that is used for the tests, the images, and is pushed to s3.

One option is that:

1. Jenkins runs the `Dockerfile` build
    `docker build -t temp .`

2. Jenkins copies the `WAR`-file from the image:
    `docker cp temp:/usr/local/tomcat/webapps/ROOT.war:/jenkins/dhis2-{channel}-{version/branch}.war`

4. Automated tests run against the Docker container
    **a)** Tests pass:
    - Jenkins pushes the validated image to hub.docker.com
    - Jenkins pushes the validated WAR-file to S3

    **b)** Tests fail: 
    - Jenkins aborts

This allows Jenkins to orchestrate the entire process, but delegates the creation of the actual `WAR` file to Docker. I think that this is beneficial, even if we want to move to another containerization technology as the entire tech infrastructure requirements are documented in the `Dockerfile`.

**Comment by varl** [comment] 2019-05-28 13:10
> I'm not sure it's as necessary to have an aliased nightly "latest" in the WAR file. If we really wanted to do that we would just have a script update an HTML link on the `releases` page to point to the latest canary (which includes the date in the filename).

Sounds good to me.

**Closed** 2019-06-06 12:20 UTC
