### ISSUE TITLE
What to use for CSS styling in apps/components

### ISSUE THREAD

**Issue by edoardo** [dhis2/notes#79] opened 2019-11-14 14:11 UTC
Let us determine a consensus on what technology to use for CSS styling for the @dhis2/front-end team.

---

# How do we determine a consensus?

I would like this discussion to move forward by considering [RFC 7282](https://tools.ietf.org/html/rfc7282):

> But _determining_ consensus and _coming to_ consensus are different things than  _having_ consensus.
>
> The distinction might be a bit subtle, but it's important.
>   
> Engineering always involves a set of tradeoffs.  It is almost certain that any time engineering choices need to be made, there will be options that appeal to some people, but are not appealing to some others.  **In determining consensus, the key is to separate those choices that are simply unappealing from those that are truly problematic.**
>
> **If at the end of the discussion some people have not gotten the choice that they prefer, but they have become convinced that the chosen solution is acceptable, albeit less appealing, they have still come to consensus.**  Consensus doesn't require that everyone is happy and agrees that the chosen solution is the best one.  Consensus is when everyone is sufficiently satisfied with the chosen solution, such that they no longer have specific objections to it.

Bold emphasis mine.

# Proposal

To anchor the discussion further, let us consider the options that we already have access to without introducing a new piece of technology to our stack.

Built into the App Platform we have support for:

- **Styled JSX**
- **CSS Modules**

We need to compile a list of concerns that we have with those before exploring other possible options out in the wild. So far I have tried to pull out the concerns noted so far in this thread, and I have "hidden" the original comments to keep it a bit flatter.

# Format for noting concerns

If we can use the following format for comments that state a concern that would help a lot when compiling the list:

```
**Concern**: <concern description>
``` 

I will copy the concern to the list in the top comment and hide the source comment to keep the thread easier to scan.

# How do we make the decision after gathering pros and cons?

To quote the RFC:

> So, in the case of a working group decision, after the initial discussion of the pros and cons of the available choices, it is most important to ask not just for objections to a particular proposal, but for the nature of those objections.  
>
> A chair who asks, "Is everyone OK with choice A?" is going to get objections. But a chair who asks, "Can anyone not live with choice A?" is more likely to only hear from folks who think that choice A is impossible to engineer given some constraints.  Following up with, What are the reasons you object to choice A?" is also essential.
>
> Then, the purported failings of the choice can be examined by the working group.  The objector might convince the rest of the group that the objections are valid and the working group might choose a different path.  Conversely, the working group might convince the objector that the concerns can be addressed, or that the choice is simply unappealing (i.e., something the objector can "live with") and not a show-stopper.  In any event, closure is much more likely to be achieved quickly by asking for and trying to accommodate the objections rather than asking for agreement.

After gathering a list of concerns, we will need to flesh them out with examples so they can actually be talked about constructively to figure out if there are ways to accommodate the concern. Then we can reach a decision that everyone can _live with_ even if it is not their personal preference. 

---

# List of concerns

1. The App Platform in the short-term uses CRA and inherits **Webpack+CSS Modules**. In the long-term we want to move away from CRA and provide our own configuration. Investing in **Webpack+CSS Modules** now locks us in to that in the long-term as well.

1. **Styled JSX** lacks a well-tested style linter plugin, whereas it is simple to integrate with **CSS Modules**.

1. When global CSS is used outside of e.g. UI Core components, there is a risk of styles bleeding in when common class names are used.

1. Developer freedom when it comes to designing components in **Styled JSX** is more opinionated than with **CSS Modules**.

1. How would one extend styles from one component in a new component?

1. There doesn't seem to be an easy way to change the underlying element without having to duplicate the component.

1. **Styled JSX** is hard to learn for developers not experienced with React.

---

_(edited by @varl)_

**Comment by Mohammer5** [comment] 2019-11-15 02:13
Personally I prefer css modules. Styled-jsx is not the nicest tech to work with.
I think we could have different techs in apps and libs as these serve different purposes.

Libraries are meant to be used by potentially anyone, so we've decided to add a css library that doesn't require the app/lib that uses it to have any kind of css processing.
But we don't need that in apps.

css modules lets us write standard css files (works in most editors/IDEs out of the box), it works well with `ui-core` as we can use classNames from the css files or overwrite ui-core internals manually/directly.

**Comment by varl** [comment] 2019-11-15 08:01
> css modules lets us write standard css files (works in most editors/IDEs out of the box), it works well with `ui-core` as we can **use classNames from the css files or overwrite ui-core internals manually/directly**.

No, that's not what the `className` prop is for. The `className` prop is an escape hatch that an app can use when all else fails. It is not the primary way to use/wrap/customize `ui-core` components.

If we use that technique all the time, it would couple an app to the internals of how a component is implemented which will stop us from refactoring the internal structure of components.

And, any developer trying to override `ui-core` components with a class would have to explore exactly what the internal structure is.

**Comment by edoardo** [comment] 2019-11-15 08:07
Yes, after discussing with @varl I changed the approach for DV options.
I already happen to wrap the `ui-core` components because I need to connect each DV option component to the Redux store, so I apply styles to the wrapper instead of trying to change the style of `ui-core` components' internals.
So far it worked well and I was able to style the DV options as per @cooper-joe sketches.

**Comment by Mohammer5** [comment] 2019-11-15 08:25
> No, that's not what the className prop is for. The className prop is an escape hatch that an app can use when all else fails. It is not the primary way to use/wrap/customize ui-core components.

Yeah, agree, that's not what I meant. I see how my choice of words was a bit poor here.. I was talking about styles bleeding in

**Comment by varl** [comment] 2019-11-15 17:32
Before diving in on specific tool choices we need to separate some terms.

## Preprocessed

Examples:

- PostCSS
- SASS
- LESS

## CSS-in-JS

Examples:

- JSS
- Emotion
- Styled Components
- Styled JSX
- CSS Modules

# CSS

Using vanilla CSS files and prepocessed CSS files generally looks the
same. We end up with a stylesheet that goes in
`build/public/css/styles.css`, and we need to refer to it from the HTML
file that acts as the entry-point, e.g. `build/public/index.html`:

```html
<link rel="stylesheet" type="text/css" href="css/styles.css">
```

Now the App can refer to all the global styles in the linked
stylesheet.

Global styles are not nice to work with, and I don't think that anyone
is interested in that approach. I bring this up to anchor the discussion
around CSS-in-JS and **avoid discussing what flavour (LESS, SASS, etc.)
of CSS to write**.

So:

**Everything that we do beyond this point though is strictly speaking
CSS-in-JS.**

# CSS with Webpack

## `style-loader`

Manually linking in stylesheets can be done, but it is tedious and error
prone and as a whole we are "over it". CreateReactApp has been kind
enough to bundle an incremental improvement with the Webpack
`style-loader` plugin that allows us to import CSS files in JavaScript
and inject them into the DOM.

```jsx
import styles from './styles.css'

// styles['a-class']
// styles['b-class']
```

## `css-loader` (CSS Modules)

The `css-loader` plugin adds in and extends the `style-loader` with                                                                                                                                   support for `@import` and `url()` so it can resolve those as well.

It also offers the ability to enable **CSS Modules** so it is possible
to locally scope CSS to components.

CSS is still written in files named `.css`, and Webpack does all the
transpiling and mapping for us.

CSS Modules requires a JS runtime piece, and Webpack injects that as
well as deals with creating a CSS to JSON mapping table for the
generated selectors.

# CSS with Styled JSX

Styled JSX, Webpack, Styled Components, Emotion in broad terms work the
same way and solve the same problem. How they go about it differ.

Styled JSX sets out to do one thing, and do it well: it gives us the
ability to write **CSS** in **JSX**. To do so "well" it:

> - Injects styles upon render
> - Only injects a certain component's style once (even if the component
> is included multiple times)
> - Removes unused styles

Styled JSX and Webpack are pure, as when we use those pieces of technology
nothing happens to our component:

#### Code

```jsx
const { className, styles } = css.resolve`
  button { color: rebeccapurple; }
`
const Button = ({ children }) => (
  <button className={className}>
      {children}
      {styles}
  </button>
)
```

#### Result

```js
function Button(_ref) {
  var children = _ref.children;
  return _react.default.createElement("button", {
    className: className,
    __source: {
      fileName: _jsxFileName,
      lineNumber: 13
    }
  }, children, styles);
}
```

This example uses the styled-jsx Babel macros to put it on level playing field
with Styled Components. Normally, we would write a slightly more concise
version without the `resolve`:
```jsx
const Button = ({ children }) => (
  <button>
      {children}

      <style jsx>{`
           button { color: rebeccapurple; }
      `}</style>
  </button>
)
```

When we use Styled Components or Emotion,  effectively wrap our
components in another API so what we get back is not an instance of
our original component. It is now wrapped in a component that makes it
an instance of Styled Components/Emotion.

#### Code

```jsx
const Button = styled.button`
  color: rebeccapurple;
`
```

#### Result

```js
{
    $$typeof: Symbol(react.forward_ref),
    render: function forwardRef(props, ref) {
    return React__default.createElement(ParentComponent, _extends({}, props, { forwardedComponent: WrappedStyledComponent, forwardedRef: ref }));
  },
    displayName: 'src__Button',
    attrs: [],
    componentStyle: {
        rules: [
            'color:rebeccapurple;'
        ],
        isStatic: false,
        componentId: 'src__Button-cdggoh-0'
    },
    foldedComponentIds: [],
    styledComponentId: 'src__Button-cdggoh-0',
    target: 'button',
    withComponent: function withComponent(tag) {
    var previousComponentId = options.componentId,
        optionsToCopy = objectWithoutProperties(options, ['componentId']);


    var newComponentId = previousComponentId && previousComponentId + '-' + (isTag(tag) ? tag : escape(getComponentName(tag)));

    var newOptions = _extends({}, optionsToCopy, {
      attrs: finalAttrs,
      componentId: newComponentId,
      ParentComponent: ParentComponent
    });

    return createStyledComponent(tag, newOptions, rules);
  },
    warnTooManyClasses: function (className) {
    if (!warningSeen) {
      generatedClasses[className] = true;
      if (Object.keys(generatedClasses).length >= LIMIT) {
        // Unable to find latestRule in test environment.
        /* eslint-disable no-console, prefer-template */
        console.warn('Over ' + LIMIT + ' classes were generated for component ' + displayName + '. \n' + 'Consider using the attrs method, together with a style object for frequently changed styles.
        warningSeen = true;
        generatedClasses = {};
      }
    }
  },
    toString: function () {
    return '.' + WrappedStyledComponent.styledComponentId;
  }
}
```

The general situation is the same for Emotion, so I am not going to
copypaste the code for it here.

That said, Styled JSX is not without its drawbacks:

- It uses a singleton in 3.x, it is to change to an instance based API
  in [4.x](https://github.com/zeit/styled-jsx/milestone/2).
- Combining development mode and production mode between lib and app is
  tricky.
- While it is possible to use e.g. Stylelint and other preprocessors
  with StyledJSX (PostCSS/LESS/SASS/etc.) it only applies to the
  static styles (styles with constants are considered static) so support
  is not complete.
- Much like JSX in the beginning, it takes some time to grok.

# Libraries

For libraries, the fact that the component's API is wrapped in another
API layer matters a great deal as it effectively locks us into a
specific framework (and worst case, all consumers).

For example, if the UI Core Button was wrapped in a Styled Component API
and someone realises that it is possible to compose with Styled
Components, then the fact that we are using Styled Components is not an
_internal_ API, it is part of our _external_ API and changes to it is a
breaking change.

With Styled JSX what we export from UI Core is a plain React component,
and as such we are in a better position to actively manage our external
API.

Since UI Core does not use Webpack, and does not force its consumers to
use it, it is not possible to leverage `css-loader` and `style-loader`
to get access to CSS Modules.

> Note that historically (pre-1.0) we had an "PostCSS CSS Modules"
> implementation before we migrated to Styled JSX, that did force our
> consumer to set up Webpack in a specific way. We wrote an injection
> mechanism to work around it (more on that later).

# Applications

For an application that will likely not have an external API, leaking
out implementation details about which style framework is used is not as
important as for a library.

That does not mean it is of no importance, as it may make it hard to
refactor and maintain over time, and there is a risk of vendor lock-in
even though it "looks like CSS". When porting UI Core from CSS Modules
to Styled JSX, which are both technologies with local CSS scope per
component, that there were a lot of visual regressions when switching,
even though the CSS itself was the same.

As long as we are using Webpack and the default CreateReactApp
configuration in the App Platform, CSS Modules is available
out-of-the-box, and as such is a viable choice.

On the other hand, choosing CSS Modules locks us into using Webpack for
bundling our applications unless we build our own CSS Module
transpilation and injection mechanism. I am not aware of any
off-the-shelf solutions for it (though the landscape changes all the
time).

We had to do this for UI Core when using CSS Modules to solve the
Webpack dependency situation and it was not very performant, nor
elegant, and lead to very complicated code in all layers: configuration,
generating mapping tables, and building components.

There is an argument for using the same style technology for both
applications and libraries since that reduces the runtime dependencies.

That said there are no severe problems with using two runtimes as long
as they use local scope CSS so using Styled JSX for libraries and CSS
Modules for applications is technically possible.

# Closing remarks

Thanks for raising this issue, I have been meaning to do a write up of
the history surrounding Styled JSX for some time now but haven't gotten
around to it.

Ignoring all CSS flavours and looking at the pros and cons, there are
two viable options that we have access to today without introducing
additional style frameworks:

1. Webpack + `css-loader` (CSS modules) + `style-loader`
1. Styled JSX

Where Webpack+CSS Modules is only viable for Applications that use
Webpack and Styled JSX is viable for contexts where we either have
control of Babel or have access to Babel Macros (e.g. CRA).

I am voting in favour of Styled JSX on the basis that I am willing to
sacrifice developer convenience (in the form of tools like Stylelint)
for a piece of technology that allows us more flexibility and does not
lock us in.

**Comment by Mohammer5** [comment] 2019-11-18 01:42
Just some thoughts:

I think we agreed that we want our components to be nothing but compositions from smaller building blocks from `ui-core`, `ui-widgets`, `ui-*`. It we truly follow this pattern and provide layout components (if responsive or not doesn't matter, still relates to #59), we should have no need for any css out apps. All we'd possible need is media queries through which we control when to show what component (which could be done [with this](https://github.com/dhis2/notes/issues/59#issuecomment-525167553)). This would move the responsive behavior to JS. If we omit styling from apps, we would not have the problem of having styles and responsive style behavior in two different places (css & js)

**Comment by ismay** [comment] 2019-11-18 08:44
Personally I am in favor of either styled components or css modules. Css modules have been a nice inbetween solution for me in the past, where it allows regular css, but is still scoped to a component.

As for css-in-js, I think styled components is way more friendlier to use than styled-jsx. There is a much bigger userbase, the documentation is a lot more extensive and the api makes a lot more sense to me. Besides that it allows linting the css, which I find a major advantage. The fact that it wraps components has never been an issue for me, whereas I've encountered a lot of limitations with regards to styled-jsx's approach. My vote would be for either styled-components or css-modules.

**Comment by varl** [comment] 2019-11-18 10:33
> I've encountered a lot of limitations with regards to styled-jsx's approach.

Could you document these limitations? Would be good to have for the discussion.

**Comment by ismay** [comment] 2019-11-18 10:56
So from my perspective I didn't really like the possibility of styles bleeding in, which you don't have with styled-components. And the inability to lint your css is a major thing I miss. I didn't really see an easy way to extend styles. And miss that there doesn't seem to be an easy way to change the underlying element without having to duplicate the component. Those are the ones I can think of off the top of my head.

On a more general level, of course you have to adapt to the api of a new lib. But I've used a lot of different approaches to do css-in-js, styled-components, glamor, emotion, etc, and the DX of styled-jsx to me just doesn't seem as nice as styled-components. That's the main thing that strikes me when I use it, that it's not something that gets out of my way. And I think that if we already have trouble with it, after having worked with it for so long and being fairly experienced in the react ecosystem, devs who are more new to the react ecosystem will definitely struggle with it. In that case a friendlier api, a more extensive ecosystem and better documentation trumps the benefits of the design goals of styled-jsx in my opinion.

**Comment by varl** [comment] 2019-11-18 11:37
> So from my perspective I didn't really like the possibility of styles bleeding in, which you don't have with styled-components.

Yes, we would run the same risk with `styled-components.

`styled-jsx` and `styled-components` are not magic, and given the same circumstances, they both allow CSS to bleed in:

Compare the two:

- https://codesandbox.io/s/styled-components-bleed-utrph
- https://codesandbox.io/s/styled-jsx-bleed-co4qw

If we mix styling solutions, we risk bleed. CSS specificity still applies for both `styled-jsx` and `styled-components. Since they share the same fundamental problem, they share the same solution, and we can still only guarantee that our styles don't leak out, but styles may bleed in.

>And the inability to lint your css is a major thing I miss.

`styled-components` has the same drawback for Stylelint as `styled-jsx` when it comes to linting: https://www.styled-components.com/docs/tooling#interpolation-tagging as they cannot use Stylelint for dynamic styles (instead they make assumptions). I know that there is a "example plugin" for `styled-jsx`, but the implementation is so trivial that it does the job. It has been on my backburner for a while but is something we can add.

> I didn't really see an easy way to extend styles.

Valid complaint. My perspective is that this is a feature and a trait I appreciate a lot with `styled-jsx`. Especially when I refactored UI core component by component (twice).

> And miss that there doesn't seem to be an easy way to change the underlying element without having to duplicate the component.

Valid complaint. We would have to implement this ourselves or use: https://www.npmjs.com/package/styled-jsx-components which would allow something like:

```
const MyButton = styled(Button)`
  padding: 32px;
  ${color}
`
```

**Comment by ismay** [comment] 2019-11-18 13:00
> styled-jsx and styled-components are not magic, and given the same circumstances, they both allow CSS to bleed in:

I can clarify what I meant here. What I meant is that we at times use classnames with styled-jsx (like `root-this`, `root-that`, etc.) and we haven't found a way around that. That risks styles bleeding in unintentionally.

Whereas with styled components you can target children without using classnames directly (https://www.styled-components.com/docs/faqs#can-i-nest-rules), so you run less risk of styles bleeding in as all the used classnames are always autogenerated. I know both still use classnames in the end, but the risk of a clash in classnames with the autogenerated ones from styled components is a lot less.

> styled-components has the same drawback for Stylelint as styled-jsx when it comes to linting: https://www.styled-components.com/docs/tooling#interpolation-tagging as they cannot use Stylelint for dynamic styles (instead they make assumptions). I know that there is a "example plugin" for styled-jsx, but the implementation is so trivial that it does the job. It has been on my backburner for a while but is something we can add.

In my experience just the static styles were a huge help though, and the assumptions that the linting plugin will make are not something that I've bothered with much. Plus it's been battle tested and contributed to for a long time. Whereas with styled-jsx we'd be the beta testers.

I do think that part of our discussion on this is a bit subjective by the way. I'm trying to be as objective as I can, but in the end I can imagine that people might still feel completely different. Maybe it's just too difficult to end up with a lib that will satisfy all, and we can just leave that choice to the user?

**Comment by Mohammer5** [comment] 2019-11-18 13:31
> We should explicitly state what troubles we are having so we can figure out if they can be resolved and how. Being vague in problem statements is not constructive.

I think a "major" problem here is that you need to have experience with `styled-jsx` in order to do the right decisions (how to split styles, how to split components). I remember that all of us were struggling with this until we got used to separate components properly ("properly" in a sense that it works well with `styled-jsx`, not that it conceptually makes sense).

<hr />

> "properly" in a sense that it works well with `styled-jsx`, not that it conceptually makes sense

Which brings me to the next point: Although `styled-jsx` allows us the following:

> I am voting in favour of Styled JSX on the basis that I am willing to sacrifice developer convenience  . . . for a piece of technology that allows us more flexibility and does not lock us in.

We're not just sacrificing developer experience, we're also sacrificing the "freedom" of designing a component in any way we see fit, they will have to adhere to the `styled-jsx` splitting-internals way or maintenance-effort will increase significantly.

**Comment by varl** [comment] 2019-12-10 08:56
Alright, it looks like momentum died down on this.

I haven't stopped thinking about it though, and while I think we could accommodate most of the concerns listed against **Styled JSX**, we are seeing that external developers struggle with React, and using **Styled JSX** effectively requires the developer to have strong React skills.

I'm going to add a proposal that's based on the discussion, and we can bring it up in #81.

**Comment by varl** [comment] 2019-12-10 08:58
# Proposal

Based on the discussion ITT, the following is a reasonable course of action:

- **Apps**: Use **CSS Modules** ([`filename.module.css`](https://github.com/facebook/create-react-app/blob/0327d8952ad3bb229c26b1a1d793b42755135b84/packages/react-scripts/config/webpack.config.js#L514-L525)) as the preferred style solution.

- **Libs**: For component libraries we still need an efficient way to ship CSS and markup as a unit so let's keep **Styled JSX** in UI libraries.

**Closed** 2019-12-20 13:02 UTC
Labels: discussion, frontend
